// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.subsystems;


import frc.robot.commands.*;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.PIDOutput;
import edu.wpi.first.wpilibj.PIDSource;


// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.Servo;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import com.revrobotics.CANSparkMax;
import com.revrobotics.CANSparkMaxLowLevel.MotorType;
import com.revrobotics.CANEncoder;

/**
 *
 */
public class Chassis extends Subsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS
    private CANEncoder LeftFrontEncoder;
    private CANEncoder LeftRearEncoder;
    private CANEncoder RightFrontEncoder;
    private CANEncoder RightRearEncoder;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
private Servo cameraServo;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    CANSparkMax LeftFrontMotor;
    CANSparkMax LeftRearMotor;
    CANSparkMax RightFrontMotor;
    CANSparkMax RightRearMotor;

    public Chassis() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
cameraServo = new Servo(0);
addChild("CameraServo",cameraServo);

        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    LeftFrontMotor = new CANSparkMax(12, MotorType.kBrushless);
    LeftRearMotor = new CANSparkMax(13, MotorType.kBrushless);
    RightFrontMotor = new CANSparkMax(14, MotorType.kBrushless);
    RightRearMotor = new CANSparkMax(15, MotorType.kBrushless);
    
    LeftFrontEncoder = LeftFrontMotor.getEncoder();
    LeftRearEncoder = LeftRearMotor.getEncoder();
    RightFrontEncoder = RightFrontMotor.getEncoder();
    RightRearEncoder = RightRearMotor.getEncoder();

    }

    @Override
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        setDefaultCommand(new DriveCommand());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    }

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CMDPIDGETTERS

    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    public void setLeftFrontMotor(double power){
        LeftFrontMotor.set(power);
    }
    public void setLeftRearMotor(double power){
        LeftRearMotor.set(power);
    }
    public void setRightFrontMotor(double power){
        RightFrontMotor.set(power);
    }
    public void setRightRearMotor(double power){
        RightRearMotor.set(power);
    }
    public String getLFEncoderPosition(){
        return "Left Front Encoder Position: " + LeftFrontEncoder.getPosition();
    }
    public String getLREncoderPosition(){
        return "Left Rear Encoder Position: " + LeftRearEncoder.getPosition();
    }
    public String getRFEncoderPosition(){
        return "Right Front Encoder Position: " + RightFrontEncoder.getPosition();
    }
    public String getRREncoderPosition(){
        return "Right Rear Encoder Position: " + RightRearEncoder.getPosition();
    }

}

