// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.commands;
import edu.wpi.first.wpilibj.command.Command;
import frc.robot.Robot;

/**
 *
 */
public class AutonomousCommand extends Command {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private final double NORMAL = 0.5;
    private final double STOP = 0.0;

    //positional variables (data)
    private final double FORWARD_MAX_ROTATIONS = 5;
    private final double BACKWARD_MAX_ROTATIONS = 5;
    private final double RIGHT_MAX_ROTATIONS = 5;
    private final double LEFT_MAX_ROTATIONS = 5;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public AutonomousCommand() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        //make sure all motors are not moving to begin with. Initialize to stop.
        // Robot.chassis.setLeftFrontMotor(STOP);
        // Robot.chassis.setLeftRearMotor(STOP);
        // Robot.chassis.setRightFrontMotor(STOP);
        // Robot.chassis.setRightRearMotor(STOP);
        
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        //while(Robot.chassis.getL < FORWARD_MAX_ROTATIONS){
            /*Robot.chassis.setLeftFrontMotor(NORMAL);
            Robot.chassis.setLeftRearMotor(NORMAL);
            Robot.chassis.setRightFrontMotor(NORMAL);
            Robot.chassis.setRightRearMotor(NORMAL);
            */
        //}
       /* while(backwardRotations < BACKWARD_MAX_ROTATIONS){
            Robot.chassis.setLeftFrontMotor(NORMAL);
            Robot.chassis.setLeftRearMotor(NORMAL);
            Robot.chassis.setRightFrontMotor(NORMAL);
            Robot.chassis.setRightRearMotor(NORMAL);
        }
        //goes forward for specific number of times before going on
       while(rightRotations < RIGHT_MAX_ROTATIONS){
        //how to do right/left? Pivot?
       }*/
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        //will execute everything in order, so no need to repeat execute.
        return true;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        //stop all motors. Command ended.
        // Robot.chassis.setLeftFrontMotor(STOP);
        // Robot.chassis.setRightFrontMotor(STOP);
        // Robot.chassis.setLeftRearMotor(STOP);
        // Robot.chassis.setRightRearMotor(STOP);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
